### ISSUE TITLE
Psych::SyntaxError: (src/_data/codebase/cloud/magento-cloud.json): found unknown escape character while parsing a quoted scalar at line 1 column 256

### ISSUE THREAD

**Issue by winds1983** [magento/devdocs#7559]
# Bug report

## Description

Configuration file: /var/www/html/magento/magento-devdocs/_config.yml
 Theme Config file: /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/devdocs-theme-13b0d9620c17/_config.yml
            Source: /var/www/html/magento/magento-devdocs/src
       Destination: /var/www/html/magento/magento-devdocs/_site
 Incremental build: enabled
      Generating... 
bundler: failed to load command: jekyll (/home/sunfeng/.rbenv/versions/2.6.6/bin/jekyll)
Psych::SyntaxError: (/var/www/html/magento/magento-devdocs/src/_data/codebase/cloud/magento-cloud.json): found unknown escape character while parsing a quoted scalar at line 1 column 256
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `parse'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `load'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `block in load_file'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `open'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `load_file'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/readers/data_reader.rb:67:in `read_data_file'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/readers/data_reader.rb:47:in `block in read_data_to'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/readers/data_reader.rb:39:in `each'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/readers/data_reader.rb:39:in `read_data_to'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/readers/data_reader.rb:44:in `block in read_data_to'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/readers/data_reader.rb:39:in `each'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/readers/data_reader.rb:39:in `read_data_to'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/readers/data_reader.rb:44:in `block in read_data_to'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/readers/data_reader.rb:39:in `each'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/readers/data_reader.rb:39:in `read_data_to'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/readers/data_reader.rb:21:in `read'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/reader.rb:19:in `read'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/site.rb:180:in `read'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/site.rb:78:in `process'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/command.rb:28:in `process_site'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/commands/build.rb:65:in `build'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/commands/build.rb:36:in `process'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/command.rb:91:in `each'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
  /home/sunfeng/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/jekyll-4.1.0/exe/jekyll:15:in `<top (required)>'
  /home/sunfeng/.rbenv/versions/2.6.6/bin/jekyll:23:in `load'
  /home/sunfeng/.rbenv/versions/2.6.6/bin/jekyll:23:in `<top (required)>'
rake aborted!
Command failed with status (1): [bundle exec jekyll serve --incremental \
 ...]
/var/www/html/magento/magento-devdocs/rakelib/preview.rake:10:in `block (2 levels) in <top (required)>'
/var/www/html/magento/magento-devdocs/Rakefile:38:in `block in <top (required)>'
Tasks: TOP => preview:all
(See full trace by running task with --trace)

### Steps to reproduce

run `rake preview`

## Expected result

Get below error:
Psych::SyntaxError: (/var/www/html/magento/magento-devdocs/src/_data/codebase/cloud/magento-cloud.json): found unknown escape character while parsing a quoted scalar at line 1 column 256

**Comment by shrielenee** [comment]
Hey @dshevtsov --- Is this something you've experienced?

**Comment by dshevtsov** [comment]
I added a Troubleshooting section about `Psych::SyntaxError` to our wiki just yesterday: [Psych::SyntaxError when running commands to preview or build the site](https://github.com/magento/devdocs/wiki/Troubleshooting#psychsyntaxerror-when-running-commands-to-preview-or-build-the-site).

**Comment by dshevtsov** [comment]
This looks like an environment related issue, otherwise it would fail before a pull request with this JSON was merged.
My first guess is that the issue is related to `rbenv`. @hguthrie, can you reproduce this issue on latest master with ruby installed by `rbenv`.

**Comment by hguthrie** [comment]
I use RBENV and I have not run in to this situation. I tried to start with a fresh clone and play with the versions to see if it messes up, but still didn't see this. I agree that the problem could be related to environment.

There are a couple of things that can cause RBENV to throw errors: outdated dependencies and outdated XCODE.

- Make sure XCODE is up to date.
- Make sure the Ruby version is set in global. `rbenv global 2.6.6`
- Check `bundle doctor` in case there is a gem problem.
- RBENV health check command: `curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash`

When you install a new version of Ruby with RBENV, you may need the shims rehashed (maps the ruby commands for all versions), so try `rbenv rehash`

You can try to restore the installed gems to a clean state and then run the rake task again:
`bundle pristine`

You can try to clean up unused gems:
`bundle clean --force`

Let me know if you need further assistance.
